### ISSUE TITLE
Microsoft.Azure.WebJobs.EventHubs.dll 4.0.0.0 is not strong named

### ISSUE THREAD

**Issue by kristofferpagels** [Azure/azure-functions-eventhubs-extension#21]
The dll released with Microsoft.Azure.WebJobs.Extensions.EventHubs 4.0.0 is not strongly named which is causing issues when we reference it. Could you please release a strongly named version of this file?

```csharp
System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred.
  Source=mscorlib
  StackTrace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions) in f:\dd\ndp\clr\src\BCL\system\threading\Tasks\Task.cs:line 2155
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification) in f:\dd\ndp\clr\src\BCL\system\threading\Tasks\Future.cs:line 567
   at System.Threading.Tasks.Task`1.get_Result() in f:\dd\ndp\clr\src\BCL\system\threading\Tasks\Future.cs:line 532
   at ...

Inner Exception 1:
FileLoadException: Could not load file or assembly 'Microsoft.Azure.WebJobs.EventHubs, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A)

Inner Exception 2:
SecurityException: Strong name validation failed. (Exception from HRESULT: 0x8013141A)
```

When looking at the dll directly with `sn.exe` I can see the following:
```
c:\>sn -vf Microsoft.Azure.WebJobs.EventHubs.dll

Microsoft (R) .NET Framework Strong Name Utility  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Microsoft.Azure.WebJobs.EventHubs.dll is a delay-signed or test-signed assembly
```

It's the same issue for Microsoft.Azure.WebJobs.ServiceBus.dll released in Microsoft.Azure.WebJobs.Extensions.ServiceBus 3.1.0

Regards
Kristoffer

**Comment by alrod** [comment]
Fixed:
https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.EventHubs/4.0.1

@kristofferpagels, thanks for  reporting
